import type { AnomalyModelInfoResponse, ModelInfoResponse, RULModelInfoResponse, VisualQualityModelInfoResponse } from "../types/api";

interface Props { modelInfo: ModelInfoResponse | null; rulModelInfo: RULModelInfoResponse | null; anomalyModelInfo: AnomalyModelInfoResponse | null; visualModelInfo: VisualQualityModelInfoResponse | null; loading: boolean; error: string | null; onRetry: () => void; }

const metricLabels: Record<string, string> = {
  roc_auc: "ROC–AUC",
  average_precision: "Average Precision",
  brier_score: "Brier Score",
  log_loss: "Log Loss",
};

export function ModelInfoPage({ modelInfo, rulModelInfo, anomalyModelInfo, visualModelInfo, loading, error, onRetry }: Props) {
  if (loading) return <div className="page-stack"><header className="page-heading compact-heading"><div><p className="eyebrow">Model governance</p><h1>Model Information</h1></div></header><div className="panel loading-panel"><span className="loader-ring" /><p>Loading versioned model metadata…</p></div></div>;
  if (error || !modelInfo) return <div className="page-stack"><header className="page-heading compact-heading"><div><p className="eyebrow">Model governance</p><h1>Model Information</h1></div></header><div className="alert alert-error" role="alert"><div><strong>Metadata unavailable</strong><span>{error ?? "No model metadata returned."}</span></div><button onClick={onRetry}>Retry</button></div></div>;

  return (
    <div className="page-stack">
      <header className="page-heading compact-heading"><div><p className="eyebrow">Model governance</p><h1>Model Information</h1><p className="page-lead">A transparent view of the model currently serving predictive-maintenance risk estimates.</p></div><span className="version-lock">Model v{modelInfo.model_version}</span></header>
      <section className="metric-grid model-metrics">
        {Object.entries(modelInfo.development_evaluation_metrics).map(([key, value]) => <article className="metric-card" key={key}><span className="metric-label">{metricLabels[key] ?? key}</span><div className="metric-value mono">{value.toFixed(4)}</div><p>{key === "brier_score" || key === "log_loss" ? "Lower is better" : "Development holdout"}</p></article>)}
      </section>
      <section className="model-info-grid">
        <article className="panel"><div className="panel-heading"><div><span className="section-kicker">Serving configuration</span><h2>Model specification</h2></div></div><dl className="spec-list"><div><dt>Family</dt><dd>{modelInfo.model_family}</dd></div><div><dt>Target</dt><dd>{modelInfo.target}</dd></div><div><dt>Calibration</dt><dd className="capitalize">{modelInfo.calibration_method}</dd></div><div><dt>Threshold version</dt><dd>v{modelInfo.threshold_version}</dd></div></dl></article>
        <article className="panel feature-panel"><div className="panel-heading"><div><span className="section-kicker">Feature contract</span><h2>Inputs & transformations</h2></div></div><h3>Raw client inputs</h3><div className="tag-list">{modelInfo.raw_input_features.map((feature) => <span key={feature}>{feature}</span>)}</div><h3>Internally engineered</h3><div className="tag-list engineered">{modelInfo.engineered_features.map((feature) => <span key={feature}>{feature}</span>)}</div></article>
      </section>
      <article className="panel interpretation-panel"><div><span className="section-kicker">Responsible use</span><h2>Development-stage interpretation</h2><p>{modelInfo.output_interpretation}</p></div><div className="warning-list">{modelInfo.methodological_warnings.map((warning, index) => <div key={`${index}-${warning}`}><span aria-hidden="true">!</span><p>{warning}</p></div>)}</div></article>
      {rulModelInfo && <section className="panel rul-model-panel"><div className="panel-heading"><div><span className="section-kicker">Module 02 · Remaining Useful Life</span><h2>{rulModelInfo.model_name}</h2></div><span className="version-lock">Model v{rulModelInfo.model_version}</span></div><dl className="spec-list"><div><dt>Family</dt><dd>{rulModelInfo.model_family}</dd></div><div><dt>Dataset</dt><dd>{rulModelInfo.dataset} · {rulModelInfo.dataset_subset}</dd></div><div><dt>Predictors</dt><dd>{rulModelInfo.predictor_count}</dd></div><div><dt>Horizon cap</dt><dd>{rulModelInfo.rul_cap} cycles</dd></div><div><dt>Full context</dt><dd>{rulModelInfo.minimum_full_context_cycles}+ cycles</dd></div><div><dt>Endpoint RMSE</dt><dd>{rulModelInfo.official_endpoint_metrics.rmse?.toFixed(2) ?? "—"}</dd></div><div><dt>Endpoint MAE</dt><dd>{rulModelInfo.official_endpoint_metrics.mae?.toFixed(2) ?? "—"}</dd></div><div><dt>Endpoint R²</dt><dd>{rulModelInfo.official_endpoint_metrics.r2?.toFixed(3) ?? "—"}</dd></div></dl><p className="fine-print">{rulModelInfo.output_interpretation}</p><div className="warning-list light-warnings">{rulModelInfo.known_limitations.map((item) => <div key={item}><span aria-hidden="true">!</span><p>{item}</p></div>)}</div></section>}
      {anomalyModelInfo && <section className="panel rul-model-panel anomaly-model-panel"><div className="panel-heading"><div><span className="section-kicker">Module 03 · Anomaly Detection</span><h2>{anomalyModelInfo.model_name}</h2></div><span className="version-lock">Model v{anomalyModelInfo.model_version}</span></div><dl className="spec-list"><div><dt>Family</dt><dd>{anomalyModelInfo.model_family}</dd></div><div><dt>Dataset</dt><dd>{anomalyModelInfo.dataset} · {anomalyModelInfo.dataset_subset}</dd></div><div><dt>Predictors</dt><dd>{anomalyModelInfo.predictor_count}</dd></div><div><dt>Boundary</dt><dd>{anomalyModelInfo.threshold_percentile}th percentile</dd></div><div><dt>Persistence</dt><dd>{anomalyModelInfo.persistence_required_count} of latest {anomalyModelInfo.persistence_window}</dd></div><div><dt>Healthy alert burden</dt><dd>{anomalyModelInfo.healthy_alert_burden.mean_pct?.toFixed(2) ?? "—"}%</dd></div><div><dt>Critical engine coverage</dt><dd>{anomalyModelInfo.critical_alert_coverage.engine_pct?.toFixed(0) ?? "—"}%</dd></div><div><dt>Median lead-time finding</dt><dd>{anomalyModelInfo.lead_time_findings.mean_median_retrospective_cycles?.toFixed(1) ?? "—"} cycles</dd></div></dl><p className="fine-print"><strong>Normal reference:</strong> {anomalyModelInfo.normal_reference_definition}</p><p className="fine-print">{anomalyModelInfo.output_interpretation}</p><div className="warning-list light-warnings">{anomalyModelInfo.known_limitations.map((item) => <div key={item}><span aria-hidden="true">!</span><p>{item}</p></div>)}</div><div className="rul-warning"><strong>Condition-monitoring caution</strong><p>{anomalyModelInfo.warning}</p></div><p className="disclaimer">{anomalyModelInfo.disclaimer}</p></section>}
      {visualModelInfo && <section className="panel rul-model-panel visual-model-panel"><div className="panel-heading"><div><span className="section-kicker">Module 04 · Visual Quality Inspection</span><h2>{visualModelInfo.model_name}</h2></div><span className="version-lock">{visualModelInfo.model_version}</span></div><dl className="spec-list"><div><dt>Family</dt><dd>{visualModelInfo.model_family}</dd></div><div><dt>Dataset/category</dt><dd>{visualModelInfo.dataset} · {visualModelInfo.category}</dd></div><div><dt>Backbone</dt><dd>{visualModelInfo.backbone} · {visualModelInfo.backbone_weights}</dd></div><div><dt>Feature layers</dt><dd>{visualModelInfo.feature_layers.join(" + ")}</dd></div><div><dt>Patch grid</dt><dd>{visualModelInfo.patch_grid.join("×")}</dd></div><div><dt>Coreset</dt><dd>{visualModelInfo.coreset_size.toLocaleString()} patches</dd></div><div><dt>Threshold</dt><dd>{visualModelInfo.threshold.toFixed(4)}</dd></div><div><dt>Image ROC–AUC</dt><dd>{visualModelInfo.benchmark_image_metrics.roc_auc?.toFixed(4) ?? "—"}</dd></div><div><dt>Average Precision</dt><dd>{visualModelInfo.benchmark_image_metrics.average_precision?.toFixed(4) ?? "—"}</dd></div><div><dt>Recall / F1</dt><dd>{visualModelInfo.benchmark_image_metrics.recall?.toFixed(4) ?? "—"} / {visualModelInfo.benchmark_image_metrics.f1?.toFixed(4) ?? "—"}</dd></div><div><dt>Pixel ROC–AUC</dt><dd>{visualModelInfo.benchmark_pixel_metrics.roc_auc?.toFixed(4) ?? "—"}</dd></div><div><dt>Pixel AP</dt><dd>{visualModelInfo.benchmark_pixel_metrics.average_precision?.toFixed(4) ?? "—"}</dd></div></dl><p className="fine-print"><strong>Threshold policy:</strong> {visualModelInfo.threshold_policy}</p><p className="fine-print"><strong>Sensitivity tradeoff:</strong> {visualModelInfo.false_positive_false_negative_tradeoff}</p><p className="fine-print">{visualModelInfo.score_interpretation}</p><div className="warning-list light-warnings">{visualModelInfo.known_limitations.map((item) => <div key={item}><span aria-hidden="true">!</span><p>{item}</p></div>)}</div><div className="rul-warning"><strong>Visual-model caution</strong><p>{visualModelInfo.warning}</p></div><p className="fine-print"><strong>Licensing:</strong> {visualModelInfo.licensing_note}</p><p className="disclaimer">{visualModelInfo.disclaimer}</p></section>}
    </div>
  );
}
